url: https://lothiandrones.co.uk
baseurl: /

title: Lothian Drones
email: lothiandrones@gmail.com
description: "Lothian Drones delivers a full suite of aerial services, from business content creation to AI-powered roof inspections. We specialize in construction site progression, 2D mapping, and high-quality video, ensuring precise updates and stunning visuals."

people:
  - name: Christopher Walton
    pic: 1
    position: Co-Founder & Director
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/christopher-walton-673783282

  - name: Ross Turner
    pic: 2
    position: Co-Founder
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/ross-turner-b334a1212

social:
  - title: instagram
    url: https://www.instagram.com/lothiandrones
  - title: linkedin
    url: https://www.linkedin.com/in/christopher-walton-673783282
  - title: linkedin
    url: https://www.linkedin.com/in/ross-turner-b334a1212

address:
  - line: West Lothian, Scotland

services:
  - Drone Photography
  - AI Roof Inspections
  - Construction Progress Tracking
  - 2D Mapping
  - Business Content Creation

markdown: kramdown
permalink: pretty
